### PR TITLE
Fix issues with Xcode 7.3

### PR DESCRIPTION
**Pull request by perryclarke**
1. Add Xcode 7.3 UUID
2. Fix problem finding the 'symbolicatecrash' utility introduced by Xcode 7.3

### CODE REVIEW

**Comment by julian-weinert** [comment]
@perryclarke Thanks for your contribution, I really appreciate it!
Please check [JFWSymbolicateViewController.m:197](https://github.com/perryclarke/CrashSymbal/blob/master/CrashSymbal/JFWSymbolicateViewController.m#L197).
Even if we found the resource using `com.apple.dt.DVTFoundation`, we are trying to set the launch path to the resource referenced by the old `com.apple.DTDeviceKitBase` identifier.

Lines 196 through 197 should read as follows

```
NSTask *symbolicationTask = [[NSTask alloc] init];
[symbolicationTask setLaunchPath:symbolicatecrashPath];
```

And also please get rid of the call to `NSLog` while you're at it ;)

**Comment by julian-weinert** [comment]
Probably we should also move the validation process to a different runtime location.
Most people won't run Xcode with a debugger attached, thus won't see the neat error message.

What would you think about testing the existence of any of the symbolicatecrash's in [JFWCrashSymbal.m:52](https://github.com/perryclarke/CrashSymbal/blob/master/CrashSymbal/JFWCrashSymbal.m#L52) and then display an `NSAlert` explaining the issue and disable the menu item afterwards.

If you think it's a good idea, go ahead and implement it, if you want.
Otherwise let me know, I'd do it then

**Comment by julian-weinert** [comment]
Merged to [develop/cc4089](https://github.com/julian-weinert/CrashSymbal/commit/cc4089a71404a076a39060922b5dcd300851103d)

**Comment by perryclarke** [comment]
Sorry was offline ... I used NSLog as it's my habit to look at the system console when plugins don't work as expected but an NSAlert works for more people.   I'm sure you can improve on my quick'n'dirty patch.

**Comment by julian-weinert** [comment]
Sure, already done ;) But thanks for the contribution either way!

**Pull request closed without merging**
